name: Release Docker image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          export FACT_DOCKER_VERSION=4.1.1
          make

      - name: Login to ghcr.io Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: |
          PREFIX_GHCR=ghcr.io/${{ github.repository_owner }}
          FACT_DOCKER_VERSION=4.1.1

          for component in backend frontend scripts
          do
              LOCAL_IMAGE=fact-core-${component}:${FACT_DOCKER_VERSION}
              REMOTE_IMAGE_GHCR=${PREFIX_GHCR}/${LOCAL_IMAGE}
              

              docker tag ${LOCAL_IMAGE} ${REMOTE_IMAGE_GHCR}
             

              docker push ${REMOTE_IMAGE_GHCR}
              
          done
